spring:
  cloud:
    gateway:
      routes:
        - id: order service
          uri: ${ORDER_SERVICE_URI}
          predicates:
            - Path=/order-service/**
            - Header=order,true
          filters:
            - AddRequestHeader=orderKey, orderValue
            - AddResponseHeader=orderKey, orderValue
        - id: customer service
          uri: ${CUSTOMER_SERVICE_URI}
          predicates:
            - Path=/customer-service/**
            - Header=customer,true
          filters:
            - AddRequestHeader=customerKey, customerValue
            - AddResponseHeader=customerKey, customerValue
        - id: product service
          uri: ${PRODUCT_SERVICE_URI}
          predicates:
            - Path=/product-service/**
            - Header=product,true
          filters:
            - AddRequestHeader=productKey, productValue
            - AddResponseHeader=productKey, productValue