server:
    port: 8888
    servlet.context-path: /config-server
spring:
  application.name: config-server
  profiles.active: dev
  cloud:
    config:
      server:
        git:
          #uri: file:///D:/MyWork/my-git-hub/spring-boot-config-server
          uri: https://github.com/rafi-gdk/spring-boot-config-server
          clone-on-start: true
          default-label: master
          skip-ssl-validation: true
management:
  security:
    enabled: false
  endpoint:
    health:
      group.custom:
        show-components: always
        show-details: always
health:
  config:
    enabled: false