apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: security-deployment
  labels:
    app: securitylabel
spec:
  replicas: 1 # Number of replicas that will be created for this deployment
  selector:
    matchLabels:
      app: securitylabel
  template:
    metadata:
      labels:
        app: securitylabel
    spec:
      containers:
        - name: security-service
          image: security-service:latest # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9001 # The port that the container is running on in the cluster
---

apiVersion: v1
kind: Service # Kubernetes resource kind we are creating
metadata:
  name: security-deployment
spec:
  selector:
    app: securitylabel
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 9001